apiVersion: v1
kind: Config
preferences: {}
clusters:
  - cluster:
      server: https://267B19AD3AD16D7FB69E88C65380ECEB.sk1.us-east-1.eks.amazonaws.com
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EUXlNekUwTVRNME5Wb1hEVE13TURReU1URTBNVE0wTlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDNFCnNEUjRMM09PQjFGSU5KVENJWUhaTUVXUUUwMWVHZmNZcnU3b1lCWG8ydFAyVlh2QVFyN1Y5QUdpSi9mVWZuQkwKZ2kxMWY2QzVXMHo5NFBENFBPSk5QMml0ckhmQ0tpdWluWXFySHNVbW9jVDg0SGRaTWdLSnJHN1UycFF3bjFwbAp1TDczQnVUcVFIbnVGYks4bUtvcjJKRG9DcHVyVmFxdDVzN0NhS2lLYUJydU91MDRBS3NEanJhWGg5N3R5SzJjClRHbWh4Um1OOS9oTy9heXhNUWNMVDlEcDM3VHVsMU9hdmZFUVZyY3JKYjNmUXhNNHduRkZuUDNISEVyS0JJOWkKWGNOc25GMjRXWnErUVpUQ3hpSGN1T3ZnSEszcE00RlNxQVUyT0ZFRGxjWEFYbWJHc2ZEUzJVSEl1SlZEZWRZLwpVNlJmNUFnY3BUbmszZGJVMllNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHeSt6cDNRdlpicEx0Z01XRmRidFVyQTZuTWsKR2hIdWVhMXhEcXk1NE01YnNZRVExUTVwQ05hUkhzems0ek04NEFEcjVSTXdkY0h2Ly9XU3VwTXRtRElDVURKVwpqVDdaYTVHbFF4ak11M0xSdmtWZmQ3Q2ttTzA0TTc2Q0l4UVVPYVFFLysyanBWZ2NPOHRmbWZwYnNGOHd6M1NuCnU2RTQ0aHYremhpWktIK3haNDJKZXhUMGVaZWZkTlBPcTIremxPMk9wUGsxeDBmcDdyUG1NSlZCdHhGRW5BT0cKRDZreXNGamltaG1Ea0p5RGRZUkNMbWdMOGJja0d2Y1BHemdpYTBMaUNudS9zdHpibmpZVFpoU2doNHlQblhRQQo2a2VtTG5Pc0tNa3R4VlM3bkprbDZaeGo4QzZEdnJMUFdaRXpHcTdDcldTU2g3UFViODBoNHFienV0dz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    name: kubernetes
users:
  - name: aws
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        command: aws
        args:
          - "eks"
          - "get-token"
          - "--cluster-name"
          - "devops7220-eks-cluster"
        env:
          - name: AWS_PROFILE
            value: "dev"
contexts:
  - context:
      cluster: kubernetes
      user: aws
    name: eks
current-context: eks

