apiVersion: v1
kind: Config
preferences: {}
clusters:
  - cluster:
      server: https://5F30EDFC2E5D0B42D8DB625F2D12B656.yl4.us-east-1.eks.amazonaws.com
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EUXlNREE1TURBeE1Gb1hEVE13TURReE9EQTVNREF4TUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVVvClgraldDeVBSRnkxczd4dUl2Yk55WUF4MmhYbGJ5ZStRTWFZQkE4Z2Z2L0pERDJrT0tnZUxac3hRRVpYSUt4SWQKKzRFSnFvWFh0a1FzRDhGTzI1UDEwcUpVU3IxN2RlSDEzWXA4YWpDRTVZcklsOUVXaWhrMVdKcEVxaTVxUVFySwo1T0FyT041ZTl1bk12VWZHRC93OTBvSkNCdk14OWgxVjFUNHdYYmsreXVYVmwvcDJzMUR5MnNCdncvNGVoMDgrCmN2eG9LUHhaS2V2SlZxejIyclBxU3VxclJHMTFJSWlmNllzQjRVaVFrbVc4YmE3aExTcGZpSVNvZklMQ0t4bmQKM3Zrd1hhWnl1RVlCRkpPN2JYdi9lUEJWdzEycXBtc01UL0NaYlBCWGp5SnlZV2NaZ1hLb2FDT2NBUmhXUGRFTgpPTERGUXFDVGZyU3Qya2dwVklNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEWUl2Vml5MXA4TWVUa0JiQ3pFMW82bkh3c2YKTU5xR250TmlOdUZ4L3JSVnluWmlZNlcrSkVDMFM4bUFiWmZiYjlDSTgxc3p3b2RmNlM2V2xtaCtER2ZRc3BjbAoyRmxQZ3B1SXRTTHBUbGh6NGhiMmRrQk40T2F5R1VaNkxvVkFmNm5hVnB2aEVocllYT0YwVzlKUms1dnlMS1ZhCjVwN1B2eUxtczhKVWp4V2RRSDk5U0N1QUdmOEg3QlVOOXROSityOWVQVTArU2gyeEV5OXJ2V0tXNjB3T1hYSm8KaFFObHhaVEJnM1lPV0VCZjBkSmRMczh3amZZbjQwOHhLdFMvNmM5ZzdQTTNXbUlzZCt5amEyMmRCTUxOVUd0egp4VUlOTjkra0tmODNwOGREbjNBQXlQNFpBek9VbHgyVlFtZHk4QUtTWWE4L3Y1OVhrM05LNE90MWNjUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    name: kubernetes
users:
  - name: aws
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        command: aws
        args:
          - "eks"
          - "get-token"
          - "--cluster-name"
          - "devops7220-eks-cluster"
        env:
          - name: AWS_PROFILE
            value: "dev"
contexts:
  - context:
      cluster: kubernetes
      user: aws
    name: eks
current-context: eks

