apiVersion: v1
kind: Config
preferences: {}
clusters:
  - cluster:
      server: https://60C4BFE4619826714433A4CA0DF6DC65.gr7.us-east-1.eks.amazonaws.com
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EUXlNREl4TkRJMU4xb1hEVE13TURReE9ESXhOREkxTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSlBlClRYN0w2MEVpN2MyWWJxcVJCeGRJdVY2TWtXTGh3NmhSa0FJR2NaQmNDeHIvUGQwbCtmZ2xYSEQzMWxVN2FTU0UKeUhNWVNWUEV3LzVFSGltQUFqVkdvenZiTDUrczRyQ05UV1duenVqM0d3SkdjMFRUWmhTSzhDQ2RZRjVnMFVycgpqSlNwcXlCUTFPaXJxWm00d1RLdis2dlduYmFCY3RMaEFsTVBZVHFTTWpVMFZKS1l1L2JYMHlBWFRVaEMwWXFhClphaWxWVDVSc21uUXg2NDBuRDBvbzl6UGFuZkRXNkt0TkM3ZUMxWDBGdUhiUDYyOUxwZXZkRTVSYnBheGpQakkKMHNzaHhmRHVPcHRFZkpkZGg1OWNlVEV2bUJsV2VFTVdlVkYzK2N0ZmdtNVZWQlJyN2t1YmtCTUhYY2JEQytYZQpObnUraTBHMnMvenYySiswaSswQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBUVc5aExZelFIeUkvUCtGb0Y1RjBxL004eVEKdFZ4bFI1UVphekRGa0l5SVdPNlpLdFpmVXl3cFg0RjNNK284Zng1VE5wMzFnMndDL1ZuVTFVb2tJSlNwaHhCTQpISDVqSEJpbHRybXhiK0E1S2pWQkliREJUUnhxVmF2ZTJSUWJPRDRoYnhIU1I0bkhCWldYZ2YrM0cxS2k4SElSCksvQ0FqY0ZJeTkrc2tYbjdDVEZJV2cxZVJCNmZRUDVjT3JIaTBIbGFkMnRXRFVUU003ZnNYaE1XaFlOWVNYUVoKbWkraVJhb0lCYXJ1cHNQaGVNaER5V2lZV0NvVFlLeVJjR255dm0xRk5XWkZ4WUdmY1gzdU5YTk9mZW9lOHZYcQpZQlh5Q0dvRGpuMklUTCt5R2VoQ2FpSSt5N2hvWDF0R2loV0dRaXZ1dkRyeW1tdjNhOVMvclRSNnFxcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    name: kubernetes
users:
  - name: aws
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        command: aws
        args:
          - "eks"
          - "get-token"
          - "--cluster-name"
          - "devops7220-eks-cluster"
        env:
          - name: AWS_PROFILE
            value: "dev"
contexts:
  - context:
      cluster: kubernetes
      user: aws
    name: eks
current-context: eks

