---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scraper
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper
            image: cyrilsebastian1811/devops7220-scraper
#            args:
#            - /bin/sh
#            - -c
#            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure